// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uasoigivpahcfpgmskxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhc29pZ2l2cGFoY2ZwZ21za3h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyODY0NTgsImV4cCI6MjA3Mzg2MjQ1OH0.qteO8YATQfP-ZFGPZnU2x2ESwL23zpcqsykGyxp2AUs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});